server:
  port: 3034
  servlet:
    context-path: /jokenpo

spring:
  application:
    name: jokenpo-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        generate_statistics: true
  main:
    banner-mode: "OFF"
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.hbm2ddl: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG

management:
  endpoints:
    beans:
      enabled: false
    web:
      exposure:
        include: health,info

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        generate_statistics: false

